### ISSUE TITLE
Clicking X button to remove an item removes a different item

### ISSUE THREAD

**Issue by linuxgarou** [phroureo/pf2e-tools#11]
If I add a specific item by level (e.g. Handwraps of Mighty Blows) to the slots on the left, then use the 'Add Random Affordable Item' button at the bottom to add an item to the center column, then try to remove that random item by clicking the X button within the item's box, the item does not disappear but the items from the slots on the left do.

If I add a random item, then start adding items to the slots on the left, then try to remove the random item, it works as expected (the random item disappears).

It seems that whatever column last had an item added to it is where the 'delete' action occurs, regardless of what X button you click.

**Comment by phroureo** [comment]
Finally got around to fixing this -- should be good to go now. Thanks for raising it!
